# Generated by Django 5.1.4 on 2025-03-11 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('username', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=40)),
            ],
            options={
                'db_table': 'admin',
            },
        ),
        migrations.CreateModel(
            name='Results',
            fields=[
                ('username', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('subject', models.CharField(max_length=40)),
                ('score', models.IntegerField()),
            ],
            options={
                'db_table': 'results',
            },
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('fname', models.CharField(default='', max_length=40)),
                ('lname', models.CharField(default='', max_length=40)),
                ('emailId', models.CharField(max_length=100)),
                ('username', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=40)),
            ],
            options={
                'db_table': 'users',
            },
        ),
        migrations.CreateModel(
            name='Questions',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('qno', models.IntegerField()),
                ('qtext', models.CharField(max_length=150)),
                ('answer', models.CharField(max_length=150)),
                ('op1', models.CharField(max_length=150)),
                ('op2', models.CharField(max_length=150)),
                ('op3', models.CharField(max_length=150)),
                ('op4', models.CharField(max_length=150)),
                ('subject', models.CharField(max_length=150)),
            ],
            options={
                'db_table': 'questions',
                'unique_together': {('qno', 'subject')},
            },
        ),
    ]
