# Generated by Django 5.1.4 on 2025-01-02 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Exam_api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Questions',
            fields=[
                ('qno', models.IntegerField(primary_key=True, serialize=False)),
                ('qtext', models.CharField(max_length=50)),
                ('answer', models.CharField(max_length=50)),
                ('op1', models.CharField(max_length=50)),
                ('op2', models.CharField(max_length=50)),
                ('op3', models.CharField(max_length=50)),
                ('op4', models.CharField(max_length=50)),
                ('subject', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'questions',
            },
        ),
    ]
