# Generated by Django 5.1.4 on 2025-01-02 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Exam_api', '0002_questions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questions',
            name='answer',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='questions',
            name='op1',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='questions',
            name='op2',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='questions',
            name='op3',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='questions',
            name='op4',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='questions',
            name='qtext',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='questions',
            name='subject',
            field=models.CharField(max_length=150),
        ),
    ]
