# Generated by Django 5.1.4 on 2025-01-09 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Exam_api', '0003_alter_questions_answer_alter_questions_op1_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('username', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=40)),
            ],
            options={
                'db_table': 'admin',
            },
        ),
    ]
