# Generated by Django 5.1.4 on 2025-01-10 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Exam_api', '0006_users_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='mobNo',
            field=models.BigIntegerField(),
        ),
    ]
