# Generated by Django 5.1.4 on 2025-01-11 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Exam_api', '0007_alter_users_mobno'),
    ]

    operations = [
        migrations.RenameField(
            model_name='users',
            old_name='name',
            new_name='fname',
        ),
        migrations.RemoveField(
            model_name='users',
            name='mobNo',
        ),
        migrations.AddField(
            model_name='users',
            name='lname',
            field=models.CharField(default='', max_length=40),
        ),
    ]
